#!/bin/bash

username=$USER
read -p "Enter Machine Password Please: " password 

# Install Anydesk

echo $password | sudo -kS bash -c "wget -qO - https://keys.anydesk.com/repos/DEB-GPG-KEY | apt-key add -"
echo $password | sudo -kS bash -c 'echo "deb http://deb.anydesk.com/ all main" > /etc/apt/sources.list.d/anydesk-stable.list'
echo $password | sudo -kS apt update -y
echo $password | sudo -kS apt install -y libgtkglext1
echo $password | sudo -kS apt install -y anydesk

echo -e "/n$(mokutil --sb-state)/n"
